name: Deploy ketos client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

defaults:
  run:
    working-directory: ./client

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.8.0

      - name: Install pnpm
        run: pnpm i --frozen-lockfile

      - name: deploy client to cloudflare pages
        run: pnpm run pages:deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
